apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
    tags.datadoghq.com/env: "dev-auto-inject"
    tags.datadoghq.com/service: "helloworld"
    tags.datadoghq.com/version: "0.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: "v1.5.0"
    spec:
      containers:
      - image: smazzone/spring-helloworld
        name: helloworld
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
spec:
  type: ClusterIP
  selector:
    app: helloworld
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-external
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
  - name: http
    port: 8080
    targetPort: 8080